[package]
name = "rustirc2"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28.0", features = ["full"] }
chrono = "0.4"
clap = "2.33"
env_logger = "0.9"
log = "0.4"

[dev-dependencies]
tokio = { version = "1.28.0", features = ["full", "test-util"] }
